export const GOT_CENTERS = 'GOT_CENTERS';

export const GOT_EMPLOYEES = 'GOT_EMPLOYEES';

export const GOT_MAIN_SERVICES = 'GOT_MAIN_SERVICES';

export const GOT_SERVICES = 'GOT_SERVICES';

export const CHOOSE_CENTER = 'CHOOSE_CENTER';

export const CHOOSE_EMPLOYEE = 'CHOOSE_EMPLOYEE';

export const CHOOSE_SERVICE = 'CHOOSE_SERVICE';